# site
title: Jaewan Lim
baseurl:
url: "http://canshot.github.io"
favicon: "/assets/sample/ico.png"
g_analytics:

# bio
header: Jaewan Lim
desc: I believe in the power of everyday-10-minuet

# posts
date_format: "%b %-d, %Y"
post_title: Story
post_date: Date
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
